apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: a3ViZWJt
  azurestorageaccountkey: REliU2VwSUVPM1haZ2dlUnNKWnBzeFh3dmhWcHNuY3NmZkRmelZGUHU2dW52Q3BOUzZWVitZSitzR1l5WEpEWnlmVnFEOEx6dkQvWlhkRjY0N2pIdXc9PQ==

---

apiVersion: v1
kind: Pod
metadata:
  name: azure
spec:
  containers:
  - image: kubernetes/pause
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
  volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: tengb
          readOnly: false