apiVersion: extensions/v1beta1
kind: Deployment
# kubectl exec bash-54967b9b79-qvrfl -i -t bash
metadata:
  name:  bash
spec:
  template:
    metadata:
      labels:
        app: bash
    spec:
      containers:
      - image:  ubuntu:latest
        name:  bash
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort:  22
          name:  ssh
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}