apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  hw-nginx
  labels:
    name:  hw-nginx
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hw-nginx
    spec:
      containers:
      - image:  nginx:latest
        name:  hw-nginx
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort:  80
          name:  mainport
      restartPolicy: Always
      #imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name:  hw-nginx
spec:
  selector:
    app:  hw-nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hw-nginx-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hw-nginx.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: hw-nginx
          servicePort: http
  - host: hw-nginx.localcluster
    http:
      paths:
      - path: /
        backend:
          serviceName: hw-nginx
          servicePort: http
  - http:
      paths:
      - path: /
        backend:
          serviceName: hw-nginx
          servicePort: http
