apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  hw-nginx-deploy
  labels:
    name:  hw-nginx-deploy
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hw-nginx-deploy-tpl
    spec:
      containers:
      - image:  nginx:latest
        name:  hw-nginx-ctl
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - name: http-ctl
          containerPort: 80
      restartPolicy: Always
      #imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name:  hw-nginx-svc
spec:
  selector:
    app:  hw-nginx-deploy-tpl
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-ctl
      name: http-svc
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hw-nginx-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hworld.ddns.net
    http:
      paths:
      - path: /
        backend:
          serviceName: hw-nginx-svc
          servicePort: http-svc
