apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: voteredis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: voteredis
    spec:
      containers:
      - name: voteredis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: voteredis
spec:
  ports:
  - port: 6379
  selector:
    app: voteredis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  votingapi
  labels:
    name:  votingapi
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  votingapi
    spec:
      containers:
      - image: aahnlcontainerregistry.azurecr.io/votingapi:#{Build.BuildId}#
        name:  votingapi
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 400Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name: RedisVoteConnString
          value: "voteredis"       
        ports:
        - containerPort: 80
          name: mainport
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name:  votingapi
spec:
  selector:
    app:  votingapi
  ports:
    - port: 80
      targetPort: mainport
      name: votingapi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: voting-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - votingapi.dev.aahg.ot
    secretName: dev-ssl
  rules:
  - host: votingapi.dev.aahg.ot
    http:
      paths:
      - path: /
        backend:
          serviceName: votingapi
          servicePort: votingapi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: voting-ingress-extern
  annotations:
    kubernetes.io/ingress.class: "public"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: votingdemo.ddns.net
    http:
      paths:
      - path: /
        backend:
          serviceName: votingapi
          servicePort: votingapi
