---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  votingapi
  labels:
    name:  votingapi
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  votingapi
    spec:
      containers:
      - image: aahnlcontainerregistry.azurecr.io/votingapi:$(Build.BuildId)
        name:  votingapi
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 400Mi
        livenessProbe:
          httpGet:
            path: /api/health_bestaatniet
            port: 80
          initialDelaySeconds: 90
          timeoutSeconds: 10
        env:
        - name: RedisVoteConnString
          value: "voteredis"       
        ports:
        - containerPort: 80
          name: mainport
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
