apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  votingapi
  labels:
    name:  votingapi
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  votingapi
    spec:
      containers:
      - image:  kubedemo/voteapi:latest
        name:  votingapi
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /api/vote
            port: 80
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/vote
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  RedisVoteConnString
          value:  "voteredis"       
        ports:
        - containerPort:  80
          name:  mainport
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always